services:
  - type: web
    name: financeai-hub
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: DATABASE_URL
        value: sqlite:///./financial_data.db
      - key: DATABASE_ECHO
        value: false
      - key: DEFAULT_LLM_PROVIDER
        value: openai
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: MAX_TOKENS
        value: 4000
      - key: TEMPERATURE
        value: 0.1
      - key: MAX_CONCURRENT_REQUESTS
        value: 100
      - key: REQUEST_TIMEOUT
        value: 30
    # Note: Add your API keys through Render dashboard for security
    # OPENAI_API_KEY, GROQ_API_KEY, ANTHROPIC_API_KEY should be set as environment variables